"""
Arcana Fusion — 牌库数据
78张塔罗牌 + 36张雷诺曼牌，中英双语
"""

# ============================================================
# 塔罗牌 — 78张
# ============================================================

TAROT_CARDS = [
    # ---- 大阿尔卡纳 (Major Arcana) 0-21 ----
    {"id": 0,  "name_zh": "愚者", "name_en": "The Fool",       "keywords_zh": "开始、天真、冒险、信任",        "keywords_en": "beginnings, innocence, adventure, trust"},
    {"id": 1,  "name_zh": "魔术师", "name_en": "The Magician",  "keywords_zh": "创造、技能、意志、资源",        "keywords_en": "creation, skill, willpower, resources"},
    {"id": 2,  "name_zh": "女祭司", "name_en": "The High Priestess","keywords_zh": "直觉、潜意识、神秘、内在知识", "keywords_en": "intuition, subconscious, mystery, inner knowledge"},
    {"id": 3,  "name_zh": "女皇", "name_en": "The Empress",    "keywords_zh": "丰饶、自然、滋养、美感",        "keywords_en": "abundance, nature, nurturing, beauty"},
    {"id": 4,  "name_zh": "皇帝", "name_en": "The Emperor",    "keywords_zh": "权威、结构、稳定、控制",        "keywords_en": "authority, structure, stability, control"},
    {"id": 5,  "name_zh": "教皇", "name_en": "The Hierophant", "keywords_zh": "传统、信仰、教导、 conformity",  "keywords_en": "tradition, faith, teaching, conformity"},
    {"id": 6,  "name_zh": "恋人", "name_en": "The Lovers",     "keywords_zh": "选择、关系、和谐、价值观",      "keywords_en": "choices, relationships, harmony, values"},
    {"id": 7,  "name_zh": "战车", "name_en": "The Chariot",    "keywords_zh": "决心、胜利、意志力、征服",      "keywords_en": "determination, victory, willpower, conquest"},
    {"id": 8,  "name_zh": "力量", "name_en": "Strength",       "keywords_zh": "勇气、内在力量、耐心、慈悲",    "keywords_en": "courage, inner strength, patience, compassion"},
    {"id": 9,  "name_zh": "隐士", "name_en": "The Hermit",     "keywords_zh": "内省、孤独、寻求、智慧",        "keywords_en": "introspection, solitude, seeking, wisdom"},
    {"id": 10, "name_zh": "命运之轮", "name_en": "Wheel of Fortune","keywords_zh": "变化、循环、命运、转折点",  "keywords_en": "change, cycles, destiny, turning point"},
    {"id": 11, "name_zh": "正义", "name_en": "Justice",        "keywords_zh": "公平、真相、因果、平衡",        "keywords_en": "fairness, truth, cause & effect, balance"},
    {"id": 12, "name_zh": "倒吊人", "name_en": "The Hanged Man","keywords_zh": "暂停、放下、新视角、牺牲",    "keywords_en": "pause, surrender, new perspective, sacrifice"},
    {"id": 13, "name_zh": "死神", "name_en": "Death",          "keywords_zh": "终结、转变、放下、新生",        "keywords_en": "endings, transformation, release, renewal"},
    {"id": 14, "name_zh": "节制", "name_en": "Temperance",     "keywords_zh": "平衡、适度、耐心、融合",        "keywords_en": "balance, moderation, patience, blending"},
    {"id": 15, "name_zh": "恶魔", "name_en": "The Devil",      "keywords_zh": "束缚、执着、欲望、阴影",        "keywords_en": "bondage, attachment, desire, shadow"},
    {"id": 16, "name_zh": "高塔", "name_en": "The Tower",      "keywords_zh": "崩塌、觉醒、剧变、解放",        "keywords_en": "collapse, awakening, upheaval, liberation"},
    {"id": 17, "name_zh": "星星", "name_en": "The Star",       "keywords_zh": "希望、灵感、宁静、指引",        "keywords_en": "hope, inspiration, serenity, guidance"},
    {"id": 18, "name_zh": "月亮", "name_en": "The Moon",       "keywords_zh": "幻觉、恐惧、潜意识、直觉",      "keywords_en": "illusion, fear, subconscious, intuition"},
    {"id": 19, "name_zh": "太阳", "name_en": "The Sun",        "keywords_zh": "喜悦、成功、活力、真实",        "keywords_en": "joy, success, vitality, truth"},
    {"id": 20, "name_zh": "审判", "name_en": "Judgement",      "keywords_zh": "觉醒、反思、召唤、重生",        "keywords_en": "awakening, reflection, calling, rebirth"},
    {"id": 21, "name_zh": "世界", "name_en": "The World",      "keywords_zh": "完成、圆满、成就、整合",        "keywords_en": "completion, fulfillment, achievement, integration"},
    # ---- 权杖牌组 (Wands) — 火元素 ----
    {"id": 22, "name_zh": "权杖ACE", "name_en": "Ace of Wands",     "keywords_zh": "灵感、新开始、创造力、激情",    "keywords_en": "inspiration, new beginning, creativity, passion"},
    {"id": 23, "name_zh": "权杖二", "name_en": "Two of Wands",      "keywords_zh": "规划、决策、远方、未来",        "keywords_en": "planning, decision, far-reaching, future"},
    {"id": 24, "name_zh": "权杖三", "name_en": "Three of Wands",    "keywords_zh": "探索、前进、远见、扩张",        "keywords_en": "exploration, progress, foresight, expansion"},
    {"id": 25, "name_zh": "权杖四", "name_en": "Four of Wands",     "keywords_zh": "庆祝、家园、和谐、成就",        "keywords_en": "celebration, home, harmony, achievement"},
    {"id": 26, "name_zh": "权杖五", "name_en": "Five of Wands",     "keywords_zh": "竞争、冲突、张力、挑战",        "keywords_en": "competition, conflict, tension, challenges"},
    {"id": 27, "name_zh": "权杖六", "name_en": "Six of Wands",      "keywords_zh": "胜利、认可、自信、好消息",      "keywords_en": "victory, recognition, confidence, good news"},
    {"id": 28, "name_zh": "权杖七", "name_en": "Seven of Wands",    "keywords_zh": "防御、坚持、勇气、抗衡",        "keywords_en": "defense, perseverance, courage, standing ground"},
    {"id": 29, "name_zh": "权杖八", "name_en": "Eight of Wands",    "keywords_zh": "速度、行动、变化、前进",        "keywords_en": "speed, action, change, forward movement"},
    {"id": 30, "name_zh": "权杖九", "name_en": "Nine of Wands",     "keywords_zh": "坚韧、警惕、最后防线、毅力",    "keywords_en": "resilience, vigilance, last stand, persistence"},
    {"id": 31, "name_zh": "权杖十", "name_en": "Ten of Wands",      "keywords_zh": "负担、压力、过度承担、责任",    "keywords_en": "burden, pressure, overcommitment, responsibility"},
    {"id": 32, "name_zh": "权杖侍从", "name_en": "Page of Wands",   "keywords_zh": "探索、热情、自由精神、消息",    "keywords_en": "exploration, enthusiasm, free spirit, message"},
    {"id": 33, "name_zh": "权杖骑士", "name_en": "Knight of Wands", "keywords_zh": "行动、冲动、冒险、追求",        "keywords_en": "action, impulsiveness, adventure, pursuit"},
    {"id": 34, "name_zh": "权杖王后", "name_en": "Queen of Wands",  "keywords_zh": "自信、热情、坚定、魅力",        "keywords_en": "confidence, warmth, determination, charisma"},
    {"id": 35, "name_zh": "权杖国王", "name_en": "King of Wands",   "keywords_zh": "领导力、远见、创业、荣誉",      "keywords_en": "leadership, vision, entrepreneurship, honor"},
    # ---- 圣杯牌组 (Cups) — 水元素 ----
    {"id": 36, "name_zh": "圣杯ACE", "name_en": "Ace of Cups",      "keywords_zh": "爱、情感、直觉、新感情",        "keywords_en": "love, emotion, intuition, new feelings"},
    {"id": 37, "name_zh": "圣杯二", "name_en": "Two of Cups",       "keywords_zh": "结合、连接、平等、共鸣",        "keywords_en": "union, connection, equality, resonance"},
    {"id": 38, "name_zh": "圣杯三", "name_en": "Three of Cups",     "keywords_zh": "庆祝、友谊、社群、欢乐",        "keywords_en": "celebration, friendship, community, joy"},
    {"id": 39, "name_zh": "圣杯四", "name_en": "Four of Cups",      "keywords_zh": "沉思、冷漠、不满足、内省",      "keywords_en": "contemplation, apathy, discontent, introspection"},
    {"id": 40, "name_zh": "圣杯五", "name_en": "Five of Cups",      "keywords_zh": "失落、悲伤、遗憾、放手",        "keywords_en": "loss, grief, regret, letting go"},
    {"id": 41, "name_zh": "圣杯六", "name_en": "Six of Cups",       "keywords_zh": "怀旧、回忆、纯真、赠予",        "keywords_en": "nostalgia, memories, innocence, giving"},
    {"id": 42, "name_zh": "圣杯七", "name_en": "Seven of Cups",     "keywords_zh": "幻象、选择、幻想、迷茫",        "keywords_en": "illusion, choices, fantasy, confusion"},
    {"id": 43, "name_zh": "圣杯八", "name_en": "Eight of Cups",     "keywords_zh": "离开、追寻、放手、转变",        "keywords_en": "departure, seeking, letting go, transition"},
    {"id": 44, "name_zh": "圣杯九", "name_en": "Nine of Cups",      "keywords_zh": "满足、如愿、幸福、梦想成真",    "keywords_en": "satisfaction, wish fulfillment, happiness, contentment"},
    {"id": 45, "name_zh": "圣杯十", "name_en": "Ten of Cups",       "keywords_zh": "幸福、家庭、和谐、圆满",        "keywords_en": "happiness, family, harmony, fulfillment"},
    {"id": 46, "name_zh": "圣杯侍从", "name_en": "Page of Cups",    "keywords_zh": "敏感、直觉、创意、邀请",        "keywords_en": "sensitivity, intuition, creativity, invitation"},
    {"id": 47, "name_zh": "圣杯骑士", "name_en": "Knight of Cups",  "keywords_zh": "浪漫、追求、理想、魅力",        "keywords_en": "romance, pursuit, idealism, charm"},
    {"id": 48, "name_zh": "圣杯王后", "name_en": "Queen of Cups",   "keywords_zh": "慈悲、包容、直觉、滋养",        "keywords_en": "compassion, nurturing, intuition, emotional depth"},
    {"id": 49, "name_zh": "圣杯国王", "name_en": "King of Cups",    "keywords_zh": "情商、冷静、智慧、掌控情绪",    "keywords_en": "emotional maturity, calm, wisdom, composure"},
    # ---- 宝剑牌组 (Swords) — 风元素 ----
    {"id": 50, "name_zh": "宝剑ACE", "name_en": "Ace of Swords",    "keywords_zh": "真理、清晰、突破、新观念",      "keywords_en": "truth, clarity, breakthrough, new idea"},
    {"id": 51, "name_zh": "宝剑二", "name_en": "Two of Swords",     "keywords_zh": "两难、回避、僵局、抉择",        "keywords_en": "difficult choice, avoidance, stalemate, dilemma"},
    {"id": 52, "name_zh": "宝剑三", "name_en": "Three of Swords",   "keywords_zh": "心痛、悲伤、创伤、真相",        "keywords_en": "heartbreak, sorrow, grief, painful truth"},
    {"id": 53, "name_zh": "宝剑四", "name_en": "Four of Swords",    "keywords_zh": "休息、恢复、沉思、疗愈",        "keywords_en": "rest, recovery, contemplation, healing"},
    {"id": 54, "name_zh": "宝剑五", "name_en": "Five of Swords",    "keywords_zh": "冲突、失败、屈辱、损耗",        "keywords_en": "conflict, defeat, humiliation, loss"},
    {"id": 55, "name_zh": "宝剑六", "name_en": "Six of Swords",     "keywords_zh": "过渡、前行、放下、疗愈之旅",    "keywords_en": "transition, moving on, release, healing journey"},
    {"id": 56, "name_zh": "宝剑七", "name_en": "Seven of Swords",   "keywords_zh": "策略、欺骗、隐密、智取",        "keywords_en": "strategy, deception, secrecy, cunning"},
    {"id": 57, "name_zh": "宝剑八", "name_en": "Eight of Swords",   "keywords_zh": "困局、自我限制、恐惧、束缚",    "keywords_en": "confinement, self-limitation, fear, restriction"},
    {"id": 58, "name_zh": "宝剑九", "name_en": "Nine of Swords",    "keywords_zh": "焦虑、噩梦、忧虑、失眠",        "keywords_en": "anxiety, nightmares, worry, insomnia"},
    {"id": 59, "name_zh": "宝剑十", "name_en": "Ten of Swords",     "keywords_zh": "终结、崩溃、触底、重生",        "keywords_en": "endings, collapse, rock bottom, rebirth"},
    {"id": 60, "name_zh": "宝剑侍从", "name_en": "Page of Swords",  "keywords_zh": "好奇、警觉、沟通、新想法",      "keywords_en": "curiosity, vigilance, communication, new ideas"},
    {"id": 61, "name_zh": "宝剑骑士", "name_en": "Knight of Swords","keywords_zh": "急迫、直率、冲动、迅速行动",    "keywords_en": "urgency, directness, impulsiveness, swift action"},
    {"id": 62, "name_zh": "宝剑王后", "name_en": "Queen of Swords", "keywords_zh": "清晰、独立、直率、洞察",        "keywords_en": "clarity, independence, directness, insight"},
    {"id": 63, "name_zh": "宝剑国王", "name_en": "King of Swords",  "keywords_zh": "理性、权威、真理、公正",        "keywords_en": "intellect, authority, truth, justice"},
    # ---- 星币牌组 (Pentacles) — 土元素 ----
    {"id": 64, "name_zh": "星币ACE", "name_en": "Ace of Pentacles",   "keywords_zh": "新机遇、繁荣、踏实、开始",    "keywords_en": "new opportunity, prosperity, grounding, beginning"},
    {"id": 65, "name_zh": "星币二", "name_en": "Two of Pentacles",    "keywords_zh": "平衡、适应、多任务、变化",      "keywords_en": "balance, adaptation, multitasking, change"},
    {"id": 66, "name_zh": "星币三", "name_en": "Three of Pentacles",  "keywords_zh": "合作、技能、团队、精进",        "keywords_en": "collaboration, skill, teamwork, craftsmanship"},
    {"id": 67, "name_zh": "星币四", "name_en": "Four of Pentacles",   "keywords_zh": "守财、稳固、控制、节俭",        "keywords_en": "conservation, stability, control, frugality"},
    {"id": 68, "name_zh": "星币五", "name_en": "Five of Pentacles",   "keywords_zh": "匮乏、困难、孤立、担忧",        "keywords_en": "lack, hardship, isolation, worry"},
    {"id": 69, "name_zh": "星币六", "name_en": "Six of Pentacles",    "keywords_zh": "慷慨、分享、给予、接受",        "keywords_en": "generosity, sharing, giving, receiving"},
    {"id": 70, "name_zh": "星币七", "name_en": "Seven of Pentacles",  "keywords_zh": "耐心、评估、投资、等待成果",    "keywords_en": "patience, assessment, investment, waiting"},
    {"id": 71, "name_zh": "星币八", "name_en": "Eight of Pentacles",  "keywords_zh": "专注、技艺、勤奋、精益求精",    "keywords_en": "diligence, craftsmanship, dedication, skill building"},
    {"id": 72, "name_zh": "星币九", "name_en": "Nine of Pentacles",   "keywords_zh": "丰盛、自足、优雅、独立",        "keywords_en": "abundance, self-sufficiency, luxury, independence"},
    {"id": 73, "name_zh": "星币十", "name_en": "Ten of Pentacles",    "keywords_zh": "传承、家族、财富、长久",        "keywords_en": "legacy, family, wealth, long-term success"},
    {"id": 74, "name_zh": "星币侍从", "name_en": "Page of Pentacles", "keywords_zh": "好学、务实、新技能、踏实",      "keywords_en": "studiousness, practicality, new skill, diligence"},
    {"id": 75, "name_zh": "星币骑士", "name_en": "Knight of Pentacles","keywords_zh": "勤奋、可靠、耐心、责任",       "keywords_en": "hard work, reliability, patience, responsibility"},
    {"id": 76, "name_zh": "星币王后", "name_en": "Queen of Pentacles","keywords_zh": "滋养、务实、丰饶、慈爱",        "keywords_en": "nurturing, practical, abundant, caring"},
    {"id": 77, "name_zh": "星币国王", "name_en": "King of Pentacles", "keywords_zh": "富足、稳固、成功、财商",        "keywords_en": "wealth, stability, success, financial acumen"},
]

# ============================================================
# 雷诺曼牌 — 36张
# ============================================================

LENORMAND_CARDS = [
    {"id": 1,  "name_zh": "骑士",     "name_en": "The Rider",       "keywords_zh": "消息、访客、新讯息、行动",        "keywords_en": "news, visitor, message, action"},
    {"id": 2,  "name_zh": "幸运草",   "name_en": "The Clover",      "keywords_zh": "好运、机会、短暂快乐、希望",      "keywords_en": "luck, opportunity, brief happiness, hope"},
    {"id": 3,  "name_zh": "船",       "name_en": "The Ship",        "keywords_zh": "旅行、远行、迁徙、探索",          "keywords_en": "travel, journey, movement, exploration"},
    {"id": 4,  "name_zh": "家",       "name_en": "The House",       "keywords_zh": "家庭、稳定、归属、安全",          "keywords_en": "home, stability, belonging, security"},
    {"id": 5,  "name_zh": "树",       "name_en": "The Tree",        "keywords_zh": "健康、成长、根基、传承",          "keywords_en": "health, growth, roots, legacy"},
    {"id": 6,  "name_zh": "云",       "name_en": "The Clouds",      "keywords_zh": "困惑、不确定、迷雾、混乱",        "keywords_en": "confusion, uncertainty, fog, turmoil"},
    {"id": 7,  "name_zh": "蛇",       "name_en": "The Snake",       "keywords_zh": "欺骗、背叛、转折、智慧",          "keywords_en": "deception, betrayal, twist, wisdom"},
    {"id": 8,  "name_zh": "棺材",     "name_en": "The Coffin",      "keywords_zh": "结束、停滞、转变、重生",          "keywords_en": "ending, stagnation, transformation, rebirth"},
    {"id": 9,  "name_zh": "花束",     "name_en": "The Bouquet",     "keywords_zh": "礼物、美好、社交、愉悦",          "keywords_en": "gift, beauty, social, pleasure"},
    {"id": 10, "name_zh": "镰刀",     "name_en": "The Scythe",      "keywords_zh": "切断、决断、突然、危险",          "keywords_en": "cutting, decision, suddenness, danger"},
    {"id": 11, "name_zh": "鞭子",     "name_en": "The Whip",        "keywords_zh": "冲突、争执、重复、激情",          "keywords_en": "conflict, argument, repetition, passion"},
    {"id": 12, "name_zh": "鸟",       "name_en": "The Birds",       "keywords_zh": "交流、对话、焦虑、社交",          "keywords_en": "communication, conversation, anxiety, socializing"},
    {"id": 13, "name_zh": "孩子",     "name_en": "The Child",       "keywords_zh": "新开始、纯真、信任、成长",        "keywords_en": "new beginning, innocence, trust, growth"},
    {"id": 14, "name_zh": "狐狸",     "name_en": "The Fox",         "keywords_zh": "狡猾、智慧、谨慎、谋略",          "keywords_en": "cunning, wisdom, caution, strategy"},
    {"id": 15, "name_zh": "熊",       "name_en": "The Bear",        "keywords_zh": "力量、保护、权威、独立",          "keywords_en": "strength, protection, authority, independence"},
    {"id": 16, "name_zh": "星星",     "name_en": "The Stars",       "keywords_zh": "方向、灵感、宁静、命运",          "keywords_en": "direction, inspiration, tranquility, destiny"},
    {"id": 17, "name_zh": "鹳鸟",     "name_en": "The Stork",       "keywords_zh": "变化、升级、新阶段、迁徙",        "keywords_en": "change, upgrade, new phase, migration"},
    {"id": 18, "name_zh": "狗",       "name_en": "The Dog",         "keywords_zh": "忠诚、友谊、陪伴、信任",          "keywords_en": "loyalty, friendship, companionship, trust"},
    {"id": 19, "name_zh": "塔",       "name_en": "The Tower",       "keywords_zh": "孤独、隔离、权威、远见",          "keywords_en": "loneliness, isolation, authority, perspective"},
    {"id": 20, "name_zh": "花园",     "name_en": "The Garden",      "keywords_zh": "社交、聚会、公众、形象",          "keywords_en": "socializing, gathering, public, image"},
    {"id": 21, "name_zh": "山",       "name_en": "The Mountain",    "keywords_zh": "阻碍、挑战、负担、坚持",          "keywords_en": "obstacle, challenge, burden, perseverance"},
    {"id": 22, "name_zh": "岔路",     "name_en": "The Crossroads",  "keywords_zh": "选择、决定、转折、机会",          "keywords_en": "choice, decision, turning point, options"},
    {"id": 23, "name_zh": "老鼠",     "name_en": "The Mice",        "keywords_zh": "损耗、焦虑、侵蚀、失去",          "keywords_en": "loss, worry, erosion, decay"},
    {"id": 24, "name_zh": "心",       "name_en": "The Heart",       "keywords_zh": "爱情、情感、热情、真诚",          "keywords_en": "love, emotion, passion, sincerity"},
    {"id": 25, "name_zh": "戒指",     "name_en": "The Ring",        "keywords_zh": "承诺、结合、循环、契约",          "keywords_en": "commitment, union, cycle, contract"},
    {"id": 26, "name_zh": "书",       "name_en": "The Book",        "keywords_zh": "知识、秘密、学习、探索",          "keywords_en": "knowledge, secrets, learning, discovery"},
    {"id": 27, "name_zh": "信",       "name_en": "The Letter",      "keywords_zh": "讯息、文件、沟通、证明",          "keywords_en": "message, document, communication, proof"},
    {"id": 28, "name_zh": "男人",     "name_en": "The Man",         "keywords_zh": "男性、阳性能量、行动力",          "keywords_en": "man, masculine energy, action"},
    {"id": 29, "name_zh": "女人",     "name_en": "The Woman",       "keywords_zh": "女性、阴性能量、直觉",            "keywords_en": "woman, feminine energy, intuition"},
    {"id": 30, "name_zh": "百合",     "name_en": "The Lily",        "keywords_zh": "平和、美德、成熟、和谐",          "keywords_en": "peace, virtue, maturity, harmony"},
    {"id": 31, "name_zh": "太阳",     "name_en": "The Sun",         "keywords_zh": "成功、活力、喜悦、光明",          "keywords_en": "success, vitality, joy, light"},
    {"id": 32, "name_zh": "月亮",     "name_en": "The Moon",        "keywords_zh": "情感、直觉、潜意识、周期",        "keywords_en": "emotion, intuition, subconscious, cycles"},
    {"id": 33, "name_zh": "钥匙",     "name_en": "The Key",         "keywords_zh": "答案、解锁、关键、命运",          "keywords_en": "answer, unlocking, key, destiny"},
    {"id": 34, "name_zh": "鱼",       "name_en": "The Fish",        "keywords_zh": "财富、流动、丰盛、水",            "keywords_en": "wealth, flow, abundance, water"},
    {"id": 35, "name_zh": "锚",       "name_en": "The Anchor",      "keywords_zh": "稳定、安全、坚守、停泊",          "keywords_en": "stability, security, steadfastness, rest"},
    {"id": 36, "name_zh": "十字架",   "name_en": "The Cross",       "keywords_zh": "命运、负担、考验、信念",          "keywords_en": "fate, burden, suffering, faith"},
]
